// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: c++.capnp

#ifndef CAPNP_INCLUDED_bdf87d7bb8304e81_
#define CAPNP_INCLUDED_bdf87d7bb8304e81_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace annotations {

}  // namespace
}  // namespace

// =======================================================================================

namespace capnp {
namespace schemas {

extern const ::capnp::_::RawSchema s_b9c6f99ebf805f2c;
extern const ::capnp::_::RawSchema s_f264a779fef191ce;

}  // namespace schemas
namespace _ {  // private


}  // namespace _ (private)
}  // namespace capnp

// =======================================================================================

namespace capnp {
namespace annotations {

// =======================================================================================

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_bdf87d7bb8304e81_
