// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: c++.capnp

#ifndef CAPNP_INCLUDED_bdf87d7bb8304e81_
#define CAPNP_INCLUDED_bdf87d7bb8304e81_

#include <capnp/generated-header-support.h>

namespace capnp {
namespace annotations {

}  // namespace
}  // namespace

// =======================================================================================

namespace capnp {
namespace schemas {

extern const ::capnp::_::RawSchema s_b9c6f99ebf805f2c;

}  // namespace schemas
namespace _ {  // private


}  // namespace _ (private)
}  // namespace capnp

// =======================================================================================

namespace capnp {
namespace annotations {

// =======================================================================================

}  // namespace
}  // namespace

#endif  // CAPNP_INCLUDED_bdf87d7bb8304e81_
