// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: c++.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 8000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(b9c6f99ebf805f2c);
CAPNP_DECLARE_SCHEMA(f264a779fef191ce);

}  // namespace schemas
}  // namespace capnp

namespace capnp {
namespace annotations {

// =======================================================================================

// =======================================================================================

}  // namespace
}  // namespace

