// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: c++.capnp

#include "c++.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<18> b_b9c6f99ebf805f2c = {
  {   0,   0,   0,   0,   3,   0,   4,   0,
     44,  95, 128, 191, 158, 249, 198, 185,
    129,  78,  48, 184, 123, 125, 248, 189,
      5,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0, 210,   0,   0,   0,
     25,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     20,   0,   0,   0,   1,   0,   1,   0,
     99,  97, 112, 110, 112,  47,  99,  43,
     43,  46,  99,  97, 112, 110, 112,  58,
    110,  97, 109, 101, 115, 112,  97,  99,
    101,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      1,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   2,   0,   1,   0,
     12,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
static const ::capnp::_::RawSchema* const d_b9c6f99ebf805f2c[] = {
};
static const ::capnp::_::RawSchema::MemberInfo m_b9c6f99ebf805f2c[] = {
};
const ::capnp::_::RawSchema s_b9c6f99ebf805f2c = {
  0xb9c6f99ebf805f2c, b_b9c6f99ebf805f2c.words, 18, d_b9c6f99ebf805f2c, m_b9c6f99ebf805f2c,
  0, 0, nullptr, nullptr
};
}  // namespace schemas
namespace _ {  // private
}  // namespace _ (private)
}  // namespace capnp
